// flow-typed signature: 3d5b1ff2df9f9a737c3d0784500376df
// flow-typed version: <<STUB>>/react-helmet_v3.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet/es/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/es/HelmetConstants' {
  declare module.exports: any;
}

declare module 'react-helmet/es/PlainComponent' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/HelmetConstants' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/PlainComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet/es/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/es/Helmet'>;
}
declare module 'react-helmet/es/HelmetConstants.js' {
  declare module.exports: $Exports<'react-helmet/es/HelmetConstants'>;
}
declare module 'react-helmet/es/PlainComponent.js' {
  declare module.exports: $Exports<'react-helmet/es/PlainComponent'>;
}
declare module 'react-helmet/lib/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/lib/Helmet'>;
}
declare module 'react-helmet/lib/HelmetConstants.js' {
  declare module.exports: $Exports<'react-helmet/lib/HelmetConstants'>;
}
declare module 'react-helmet/lib/PlainComponent.js' {
  declare module.exports: $Exports<'react-helmet/lib/PlainComponent'>;
}
