// flow-typed signature: 3c43157defbffef20a9df502e6449786
// flow-typed version: <<STUB>>/sanitize.css_v4.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}

declare module 'sanitize.css/sanitize.css' {
  declare module.exports: any;
}
